### ISSUE TITLE
Google provider : error code 6

### ISSUE THREAD

**Issue by lunanovaz** [mistic100/Piwigo-Social-Connect#12]
Piwigo version: 2.8.3
Social Connect version: 2.2.2

Since few weeks it's not possible any more to login through Google.
It failed on path : /plugins/oAuth/auth.php?provider=Google&openid_identifier=&init_auth=1# 
with Error code : 6

**Comment by uhei** [comment]
Same here too. Also with Piwigo 2.8.3 and Socal Connect version 2.2.2

**Comment by lunanovaz** [comment]
I have been able to test successfully : twitter, yahoo, Live
So I have the feeling that the library used hybridauth is not working any more with google and needs to be updated.

Which version of php are you using ?
Mine is 5.6.29

**Comment by lunanovaz** [comment]
I've isolated the error at OAuth2Client level.

That allowed me to solve the issue by replacing the OAuth lib in thirdparty folder by a more recent version from hybridauth (2.8.2) : https://github.com/hybridauth/hybridauth/releases
This release is effectively correcting a OAuth2Client [bug](https://github.com/hybridauth/hybridauth/issues/694) implying issue with Google OAuth2.

This is just a temporary fix, the correct fix should be to upgrade the whole hybridauth library.
I've tried quickly to do it but that was over my competencies/time available.

**Comment by uhei** [comment]
Great to hear that.
Have you only replaced ./piwigo/plugins/oAuth/include/hybridauth with the 2.8.2 release of hybridauth? Or did you change more files?

**Comment by lunanovaz** [comment]
I've only replaced : ./piwigo/plugins/oAuth/include/hybridauth/Hybrid/thirdparty/OAuth with the equivalent from 2.8.2 release of hybridauth.
Replacing whole hybridauth wasn't working as-is ... and would require more effort.

**Comment by uhei** [comment]
@lunanovaz Thanks a lot for your help! After replacing the OAuth directory authentication is working again.

**Comment by mistic100** [comment]
I don't have time to update the whole librayr so I just pulled the new OAuth2 client.
Thank you for the investigation

**Comment by lunanovaz** [comment]
Thanks mistic100.
I've updated the plugin with your version but google oauth is failing again. I may have done one step wrong but can't find what.

- updated first through piwigo admin ui
- tried manually unzipping the whole plugin and replacing my version

I've even checked the oAuth folder which is correctly updated.

So i'm back again to Error code 6 : "User profile request failed! Google returned an invalid response."

**Comment by mistic100** [comment]
Is this file the same on your system ?
https://github.com/mistic100/Piwigo-Social-Connect/blob/master/include/hybridauth/Hybrid/thirdparty/OAuth/OAuth2Client.php

**Comment by teknolai** [comment]
Hi @mistic100!

After the update to the latest version (of both Piwigo and Social Connect) I am still experiencing this error code 6. My OAuth2Client.php is the same as the one you linked to in your previous message.

Any suggestions for what to do?

Thanks,
Erik

**Comment by ftheoleyre** [comment]
Hi @mistic100!
I also proceed to the update, and I have the error code 6.
With a git clone of your repository, same result. 

Thus, I still have the same problem as @teknolai  I guess

Thanks,
Fabrice

**Comment by mistic100** [comment]
Sorry I don't have time for this issue.

**Comment by lunanovaz** [comment]
I think I've got ! And it doesn't seem to be related to the updated code.
Putting the library in debug, I've the following error message in the logs

> Access Not Configured. Google+ API has not been used in project ... before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/plus/overview?project=... then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry

So I've tried the following operation which has solved the issue :
- Going in Google developers console / Library / Google+ API (following previous link)
- Enabling the API.

Let me know if it works for you too.

**Comment by teknolai** [comment]
Brilliant, that solved the problem for me as well.

It seems like Google has updated their TOS and required me to accept the
new terms before I could enable the API again.

Thank you very much for looking into it and æ solving this issue!

Med vennlig hilsen | Best Regards
Erik Korme

17. feb. 2017 22.20 skrev "lunanovaz" <notifications@github.com>:

**Comment by lunanovaz** [comment]
Great !! 
So strange that it was updated at the same time when we updated the plugin.

**Comment by ftheoleyre** [comment]
Fantastic, it works!
I was convinced I already tried to remove and reactivate my API on google developers…

Many thanks for solving this issue. I use intensively your plugin...

Best regards,
Fabrice

**Comment by mistic100** [comment]
Thank you, I will update the guide
